[package]
name = "warp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "*"
tokio = { version = "1.1.0", features = ["full"] }
futures = "*"
